### ISSUE TITLE
build step fails

### ISSUE THREAD

**Issue by nkabir** [DavidVujic/python-polylith-example-uv#1]
Thank you for `uv` support. I am trying to build a project from the sample `uv` repository but encountering this error:

```
uvx --from build pyproject-build --installer uv
```
in `my_aws_lambda_project`, there's an error

```
* Creating isolated environment: venv+uv...
* Using external uv from /home/linuxbrew/.linuxbrew/bin/uv
* Installing packages in isolated environment:
  - hatch-polylith-bricks
  - hatchling
* Getting build dependencies for sdist...
* Building sdist...
* Building wheel from sdist
* Creating isolated environment: venv+uv...
* Using external uv from /home/linuxbrew/.linuxbrew/bin/uv
* Installing packages in isolated environment:
  - hatch-polylith-bricks
  - hatchling
* Getting build dependencies for wheel...
* Building wheel...
Traceback (most recent call last):
  File "/home/nkabir/.cache/uv/archive-v0/EAmSSo4owl6zHsU9BX1nZ/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
    main()
  File "/home/nkabir/.cache/uv/archive-v0/EAmSSo4owl6zHsU9BX1nZ/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in main
    json_out["return_val"] = hook(**hook_input["kwargs"])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nkabir/.cache/uv/archive-v0/EAmSSo4owl6zHsU9BX1nZ/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 280, in build_wheel
    return _build_backend().build_wheel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-ggazfner/lib/python3.12/site-packages/hatchling/build.py", line 58, in build_wheel
    return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-ggazfner/lib/python3.12/site-packages/hatchling/builders/plugin/interface.py", line 155, in build
    artifact = version_api[version](directory, **build_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-ggazfner/lib/python3.12/site-packages/hatchling/builders/wheel.py", line 475, in build_standard
    for included_file in self.recurse_included_files():
  File "/tmp/build-env-ggazfner/lib/python3.12/site-packages/hatchling/builders/plugin/interface.py", line 176, in recurse_included_files
    yield from self.recurse_selected_project_files()
  File "/tmp/build-env-ggazfner/lib/python3.12/site-packages/hatchling/builders/plugin/interface.py", line 180, in recurse_selected_project_files
    if self.config.only_include:
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-ggazfner/lib/python3.12/site-packages/hatchling/builders/config.py", line 806, in only_include
    only_include = only_include_config.get('only-include', self.default_only_include()) or self.packages
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-ggazfner/lib/python3.12/site-packages/hatchling/builders/wheel.py", line 260, in default_only_include
    return self.default_file_selection_options.only_include
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nkabir/.local/share/uv/python/cpython-3.12.0-linux-x86_64-gnu/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-ggazfner/lib/python3.12/site-packages/hatchling/builders/wheel.py", line 248, in default_file_selection_options
    raise ValueError(message)
ValueError: Unable to determine which files to ship inside the wheel using the following heuristics: https://hatch.pypa.io/latest/plugins/builder/wheel/#default-file-selection

The most likely cause of this is that there is no directory that matches the name of your project (my_aws_lambda_project).

At least one file selection option must be defined in the `tool.hatch.build.targets.wheel` table, see: https://hatch.pypa.io/latest/config/build/

As an example, if you intend to ship a directory named `foo` that resides within a `src` directory located at the root of your project, you can define the following:

[tool.hatch.build.targets.wheel]
packages = ["src/foo"]

ERROR Backend subprocess exited when trying to invoke build_wheel

```

**Comment by DavidVujic** [comment]
Thank you for reporting this issue @nkabir!

I have updated the example projects with the necessary `pyproject.toml` config. I think this is caused by a behavior change in `uv` and I will update the Polylith tool (and docs) so it will create the proper template too.

The projects need this additional config:
```toml
[tool.hatch.build.targets.wheel]
packages = ["set_the_top_namespace_here"]

[tool.hatch.build.hooks.polylith-bricks]
```

**Comment by DavidVujic** [comment]
The example repo should work as expected now, after the merge of #2. Please reopen if you still have issues! 🙏 

Current ongoing work for the Polylith tool: https://github.com/DavidVujic/python-polylith/issues/282

**Comment by DavidVujic** [comment]
I found out that `uv` is updated with a `build` command, and there it is possible to control the output. The docs are updated, with info about `uv build --wheel` and also for the use case when building _sdists_ where the extra "packages" is needed. This is not needed for building wheels.

(no action in the polylith tooling needed)
